version: "3.9"
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${DB_NAME}'" ]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - default

  django:
    build:
      context: ./
      dockerfile: ./docker/local.Dockerfile
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - './:/var/www/html/'
    env_file:
      - ./.env
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - default

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - '${APP_PORT:-80}:80'
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/static/:/var/www/html/app/static/
      - ./app/media/:/var/www/html/app/media/
    depends_on:
      - django
    links:
      - django
    networks:
      - default

networks:
  default:
    driver: bridge