version: "3.9"
services:
  postgres:
    image: postgres:15
    restart: on-failure
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${DB_NAME}'" ]
      interval: 10s
      timeout: 3s
      retries: 3
    container_name: pay2u-postgres
    networks:
      - default

  django:
    image: drode1/pay2u_backend:latest
    restart: on-failure
    volumes:
      - ./media/:/var/www/html/app/media/
      - ./logs:/var/www/html/app/logs/
    env_file:
      - ./.env
    depends_on:
      - postgres
    container_name: pay2u-django
    networks:
      - default

  nginx:
    image: nginx:1.21.3-alpine
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static/:/var/www/html/app/static/
      - ./media/:/var/www/html/app/media/
    depends_on:
      - django
    container_name: pay2u-nginx
    networks:
      - default

networks:
  default:
    external: true
    name: drodel-net
